/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './ad.component.ngfactory';
import * as i2 from './ad.component';
import * as i3 from './ad.service';
import * as i4 from '../image.service';
import * as i5 from '../map/map.component.ngfactory';
import * as i6 from '../map/map.component';
import * as i7 from '../map/map.service';
import * as i8 from './category.service';
import * as i9 from '@angular/router';
import * as i10 from '@angular/common';
import * as i11 from './ad-index.component';
const styles_AdIndexComponent:any[] = ([] as any[]);
export const RenderType_AdIndexComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_AdIndexComponent,data:{}});
function View_AdIndexComponent_1(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,0,(null as any),(null as any),1,'my-ad',([] as any[]),
      (null as any),(null as any),(null as any),i1.View_AdComponent_0,i1.RenderType_AdComponent)),
      i0.ɵdid(1,114688,(null as any),0,i2.AdComponent,[i3.AdService,i4.ImageService],
          {ad:[0,'ad']},(null as any))],(_ck,_v) => {
    const currVal_0:any = _v.context.$implicit;
    _ck(_v,1,0,currVal_0);
  },(null as any));
}
export function View_AdIndexComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,0,(null as any),(null as any),1,'app-map',([] as any[]),
      (null as any),(null as any),(null as any),i5.View_MapComponent_0,i5.RenderType_MapComponent)),
      i0.ɵdid(1,114688,(null as any),0,i6.MapComponent,[i7.MapService,i8.CategoryService,
          i3.AdService,i9.Router],(null as any),(null as any)),(_l()(),i0.ɵted(-1,
          (null as any),['\n\n'])),(_l()(),i0.ɵeld(3,0,(null as any),(null as any),
          10,'div',[['class','container']],(null as any),(null as any),(null as any),
          (null as any),(null as any))),(_l()(),i0.ɵted(-1,(null as any),['\n    '])),
      (_l()(),i0.ɵeld(5,0,(null as any),(null as any),4,'span',[['class','text-center']],
          (null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i0.ɵted(-1,(null as any),['\n        '])),(_l()(),i0.ɵeld(7,0,(null as any),
          (null as any),1,'h2',[['class','padding-bottom-md']],(null as any),(null as any),
          (null as any),(null as any),(null as any))),(_l()(),i0.ɵted(-1,(null as any),
          ['Ultimele cereri adaugate:'])),(_l()(),i0.ɵted(-1,(null as any),['\n    '])),
      (_l()(),i0.ɵted(-1,(null as any),['\n    '])),(_l()(),i0.ɵand(16777216,(null as any),
          (null as any),1,(null as any),View_AdIndexComponent_1)),i0.ɵdid(12,802816,
          (null as any),0,i10.NgForOf,[i0.ViewContainerRef,i0.TemplateRef,i0.IterableDiffers],
          {ngForOf:[0,'ngForOf']},(null as any)),(_l()(),i0.ɵted(-1,(null as any),
          ['\n']))],(_ck,_v) => {
    var _co:i11.AdIndexComponent = _v.component;
    _ck(_v,1,0);
    const currVal_0:any = _co.lastAds;
    _ck(_v,12,0,currVal_0);
  },(null as any));
}
export function View_AdIndexComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,0,(null as any),(null as any),1,'ad-index',([] as any[]),
      (null as any),(null as any),(null as any),View_AdIndexComponent_0,RenderType_AdIndexComponent)),
      i0.ɵdid(1,114688,(null as any),0,i11.AdIndexComponent,[i3.AdService],(null as any),
          (null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const AdIndexComponentNgFactory:i0.ComponentFactory<i11.AdIndexComponent> = i0.ɵccf('ad-index',
    i11.AdIndexComponent,View_AdIndexComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvQ2F0YWxpbi9EZXNrdG9wL1Byb2llY3QgbGljZW50YS9hc3NldHMvYXBwL2FkL2FkLWluZGV4LmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9Vc2Vycy9DYXRhbGluL0Rlc2t0b3AvUHJvaWVjdCBsaWNlbnRhL2Fzc2V0cy9hcHAvYWQvYWQtaW5kZXguY29tcG9uZW50LnRzIiwibmc6Ly8vQzovVXNlcnMvQ2F0YWxpbi9EZXNrdG9wL1Byb2llY3QgbGljZW50YS9hc3NldHMvYXBwL2FkL2FkLWluZGV4LmNvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovVXNlcnMvQ2F0YWxpbi9EZXNrdG9wL1Byb2llY3QgbGljZW50YS9hc3NldHMvYXBwL2FkL2FkLWluZGV4LmNvbXBvbmVudC50cy5BZEluZGV4Q29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPGFwcC1tYXA+PC9hcHAtbWFwPlxyXG5cclxuPGRpdiBjbGFzcz1cImNvbnRhaW5lclwiPlxyXG4gICAgPHNwYW4gY2xhc3M9XCJ0ZXh0LWNlbnRlclwiPlxyXG4gICAgICAgIDxoMiBjbGFzcz1cInBhZGRpbmctYm90dG9tLW1kXCI+VWx0aW1lbGUgY2VyZXJpIGFkYXVnYXRlOjwvaDI+XHJcbiAgICA8L3NwYW4+XHJcbiAgICA8bXktYWQgW2FkXT1cImN1cnJlbnRBZFwiICpuZ0Zvcj1cImxldCBjdXJyZW50QWQgb2YgbGFzdEFkc1wiPjwvbXktYWQ+XHJcbjwvZGl2PiIsIjxhZC1pbmRleD48L2FkLWluZGV4PiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztvQkNNSTtNQUFBO2FBQUE7VUFBQTtJQUFPO0lBQVAsV0FBTyxTQUFQOzs7O29CQU5KO01BQUE7YUFBQTtnQ0FBQSwrQkFBbUI7VUFBQSx5QkFFbkI7VUFBQTtVQUFBLDhCQUF1QjtNQUNuQjtVQUFBO01BQTBCLGtEQUN0QjtVQUFBO1VBQUEsNENBQThCO1VBQUEsZ0NBQThCO01BQ3pELDhDQUNQO1VBQUEsK0RBQUE7VUFBQTtVQUFBLHVDQUFrRTtVQUFBOztJQU50RTtJQU00QjtJQUF4QixZQUF3QixTQUF4Qjs7OztvQkNOSjtNQUFBO2FBQUE7VUFBQTtJQUFBOzs7OyJ9
