/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './ad.component.ngfactory';
import * as i2 from './ad.component';
import * as i3 from './ad.service';
import * as i4 from '../image.service';
import * as i5 from '@angular/common';
import * as i6 from '../pagination/pagination.component.ngfactory';
import * as i7 from '../pagination/pagination.component';
import * as i8 from './ad-list.component';
import * as i9 from '../search/search.service';
const styles_AdListComponent:any[] = ([] as any[]);
export const RenderType_AdListComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_AdListComponent,data:{}});
function View_AdListComponent_2(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,0,(null as any),(null as any),1,'my-ad',([] as any[]),
      (null as any),(null as any),(null as any),i1.View_AdComponent_0,i1.RenderType_AdComponent)),
      i0.ɵdid(1,114688,(null as any),0,i2.AdComponent,[i3.AdService,i4.ImageService],
          {ad:[0,'ad']},(null as any))],(_ck,_v) => {
    const currVal_0:any = _v.context.$implicit;
    _ck(_v,1,0,currVal_0);
  },(null as any));
}
function View_AdListComponent_1(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,0,(null as any),(null as any),4,'div',[['class',
      'container']],(null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i0.ɵted(-1,(null as any),['\n    '])),(_l()(),i0.ɵand(16777216,(null as any),
          (null as any),1,(null as any),View_AdListComponent_2)),i0.ɵdid(3,802816,
          (null as any),0,i5.NgForOf,[i0.ViewContainerRef,i0.TemplateRef,i0.IterableDiffers],
          {ngForOf:[0,'ngForOf']},(null as any)),(_l()(),i0.ɵted(-1,(null as any),
          ['\n']))],(_ck,_v) => {
    var _co:any = _v.component;
    const currVal_0:any = _co.ads;
    _ck(_v,3,0,currVal_0);
  },(null as any));
}
function View_AdListComponent_3(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵted(-1,(null as any),['\n    '])),(_l()(),i0.ɵeld(1,
      0,(null as any),(null as any),4,'div',[['class','container']],(null as any),
      (null as any),(null as any),(null as any),(null as any))),(_l()(),i0.ɵted(-1,
      (null as any),['\n        '])),(_l()(),i0.ɵeld(3,0,(null as any),(null as any),
      1,'div',[['class','alert alert-warning text-center']],(null as any),(null as any),
      (null as any),(null as any),(null as any))),(_l()(),i0.ɵted(-1,(null as any),
      ['Nu exista nicio cerere activa :('])),(_l()(),i0.ɵted(-1,(null as any),['\n    '])),
      (_l()(),i0.ɵted(-1,(null as any),['\n']))],(null as any),(null as any));
}
export function View_AdListComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵand(16777216,(null as any),(null as any),1,(null as any),
      View_AdListComponent_1)),i0.ɵdid(1,16384,(null as any),0,i5.NgIf,[i0.ViewContainerRef,
      i0.TemplateRef],{ngIf:[0,'ngIf'],ngIfElse:[1,'ngIfElse']},(null as any)),(_l()(),
      i0.ɵted(-1,(null as any),['\n'])),(_l()(),i0.ɵand(0,[['noAds',2]],(null as any),
      0,(null as any),View_AdListComponent_3)),(_l()(),i0.ɵted(-1,(null as any),['\n\n'])),
      (_l()(),i0.ɵeld(5,0,(null as any),(null as any),1,'my-pagination',([] as any[]),
          (null as any),(null as any),(null as any),i6.View_PaginationComponent_0,
          i6.RenderType_PaginationComponent)),i0.ɵdid(6,49152,(null as any),0,i7.PaginationComponent,
          ([] as any[]),(null as any),(null as any))],(_ck,_v) => {
    var _co:i8.AdListComponent = _v.component;
    const currVal_0:any = (((_co.ads == null)? (null as any): _co.ads.length) > 0);
    const currVal_1:any = i0.ɵnov(_v,3);
    _ck(_v,1,0,currVal_0,currVal_1);
  },(null as any));
}
export function View_AdListComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,0,(null as any),(null as any),1,'my-ad-list',
      ([] as any[]),(null as any),(null as any),(null as any),View_AdListComponent_0,
      RenderType_AdListComponent)),i0.ɵdid(1,114688,(null as any),0,i8.AdListComponent,
      [i3.AdService,i9.SearchService],(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const AdListComponentNgFactory:i0.ComponentFactory<i8.AdListComponent> = i0.ɵccf('my-ad-list',
    i8.AdListComponent,View_AdListComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvQ2F0YWxpbi9EZXNrdG9wL1Byb2llY3QgbGljZW50YS9hc3NldHMvYXBwL2FkL2FkLWxpc3QuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L1VzZXJzL0NhdGFsaW4vRGVza3RvcC9Qcm9pZWN0IGxpY2VudGEvYXNzZXRzL2FwcC9hZC9hZC1saXN0LmNvbXBvbmVudC50cyIsIm5nOi8vL0M6L1VzZXJzL0NhdGFsaW4vRGVza3RvcC9Qcm9pZWN0IGxpY2VudGEvYXNzZXRzL2FwcC9hZC9hZC1saXN0LmNvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovVXNlcnMvQ2F0YWxpbi9EZXNrdG9wL1Byb2llY3QgbGljZW50YS9hc3NldHMvYXBwL2FkL2FkLWxpc3QuY29tcG9uZW50LnRzLkFkTGlzdENvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxkaXYgY2xhc3M9XCJjb250YWluZXJcIiAqbmdJZj1cImFkcz8ubGVuZ3RoID4gMDsgZWxzZSBub0Fkc1wiPlxyXG4gICAgPG15LWFkIFthZF09XCJjdXJyZW50QWRcIiAqbmdGb3I9XCJsZXQgY3VycmVudEFkIG9mIGFkc1wiPjwvbXktYWQ+XHJcbjwvZGl2PlxyXG48bmctdGVtcGxhdGUgI25vQWRzPlxyXG4gICAgPGRpdiBjbGFzcz1cImNvbnRhaW5lclwiPlxyXG4gICAgICAgIDxkaXYgY2xhc3M9XCJhbGVydCBhbGVydC13YXJuaW5nIHRleHQtY2VudGVyXCI+TnUgZXhpc3RhIG5pY2lvIGNlcmVyZSBhY3RpdmEgOig8L2Rpdj5cclxuICAgIDwvZGl2PlxyXG48L25nLXRlbXBsYXRlPlxyXG5cclxuPG15LXBhZ2luYXRpb24+PC9teS1wYWdpbmF0aW9uPiIsIjxteS1hZC1saXN0PjwvbXktYWQtbGlzdD4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O29CQ0NJO01BQUE7YUFBQTtVQUFBO0lBQU87SUFBUCxXQUFPLFNBQVA7Ozs7b0JBREo7TUFBQTtNQUEyRCw4Q0FDdkQ7VUFBQSw4REFBQTtVQUFBO1VBQUEsdUNBQThEO1VBQUE7O0lBQXRDO0lBQXhCLFdBQXdCLFNBQXhCOzs7O29CQUVnQiw4Q0FDaEI7TUFBQTtNQUFBLDBEQUF1QjtNQUFBLCtCQUNuQjtNQUFBO01BQUEsNENBQTZDO01BQUEsdUNBQXNDO01BQ2pGOzs7b0JBTlY7TUFBQSxnQ0FBQTtvQkFBQSwyREFFTTthQUFBLDJCQUNOO01BQUEseUNBSWM7TUFFZDtVQUFBOzJDQUFBLFVBQUE7VUFBQTs7SUFUdUI7SUFBQTtJQUF2QixXQUF1QixtQkFBdkI7Ozs7b0JDQUE7TUFBQTtnQ0FBQSxVQUFBO01BQUE7SUFBQTs7OzsifQ==
