/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '@angular/common';
import * as i2 from './pagination.component';
const styles_PaginationComponent:any[] = ['.pagination[_ngcontent-%COMP%] {\n            display: inline-block;\n        }\n\n        .pagination[_ngcontent-%COMP%]   a[_ngcontent-%COMP%] {\n            color: black;\n            float: left;\n            padding: 8px 16px;\n        }\n\n        .pagination[_ngcontent-%COMP%]   a.active[_ngcontent-%COMP%] {\n            background-color: #4CAF50;\n            color: white;\n        }\n\n        .pagination[_ngcontent-%COMP%]   a[_ngcontent-%COMP%]:hover:not(.active) {\n            background-color: #ddd;\n        }\n\n        .pagination[_ngcontent-%COMP%]   a[_ngcontent-%COMP%]:hover:not(.active):nth-last-child(2) {\n            background: #fff;\n        }\n\n        .row[_ngcontent-%COMP%]   .pagination[_ngcontent-%COMP%] {\n            margin-bottom: 0px;\n        }'];
export const RenderType_PaginationComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:0,
    styles:styles_PaginationComponent,data:{}});
function View_PaginationComponent_1(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,0,(null as any),(null as any),1,'a',[['href',
      '#']],(null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i0.ɵted(1,(null as any),['','']))],(null as any),(_ck,_v) => {
    const currVal_0:any = _v.context.$implicit;
    _ck(_v,1,0,currVal_0);
  });
}
export function View_PaginationComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵted(-1,(null as any),['\n        '])),(_l()(),i0.ɵeld(1,
      0,(null as any),(null as any),17,'div',[['class','container']],(null as any),
      (null as any),(null as any),(null as any),(null as any))),(_l()(),i0.ɵted(-1,
      (null as any),['\n            '])),(_l()(),i0.ɵeld(3,0,(null as any),(null as any),
      14,'div',[['class','row text-center']],(null as any),(null as any),(null as any),
      (null as any),(null as any))),(_l()(),i0.ɵted(-1,(null as any),['\n                '])),
      (_l()(),i0.ɵeld(5,0,(null as any),(null as any),11,'div',[['class','pagination']],
          (null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i0.ɵted(-1,(null as any),['\n                    '])),(_l()(),i0.ɵeld(7,
          0,(null as any),(null as any),1,'a',[['href','#']],(null as any),(null as any),
          (null as any),(null as any),(null as any))),(_l()(),i0.ɵted(-1,(null as any),
          ['«'])),(_l()(),i0.ɵted(-1,(null as any),['\n                    '])),(_l()(),
          i0.ɵand(16777216,(null as any),(null as any),1,(null as any),View_PaginationComponent_1)),
      i0.ɵdid(11,802816,(null as any),0,i1.NgForOf,[i0.ViewContainerRef,i0.TemplateRef,
          i0.IterableDiffers],{ngForOf:[0,'ngForOf']},(null as any)),(_l()(),i0.ɵted(-1,
          (null as any),['\n                    '])),(_l()(),i0.ɵted(-1,(null as any),
          ['\n                    '])),(_l()(),i0.ɵeld(14,0,(null as any),(null as any),
          1,'a',[['href','#']],(null as any),(null as any),(null as any),(null as any),
          (null as any))),(_l()(),i0.ɵted(-1,(null as any),['»'])),(_l()(),i0.ɵted(-1,
          (null as any),['\n                '])),(_l()(),i0.ɵted(-1,(null as any),
          ['\n            '])),(_l()(),i0.ɵted(-1,(null as any),['\n        '])),(_l()(),
          i0.ɵted(-1,(null as any),['\n    ']))],(_ck,_v) => {
    var _co:i2.PaginationComponent = _v.component;
    const currVal_0:any = _co.pages;
    _ck(_v,11,0,currVal_0);
  },(null as any));
}
export function View_PaginationComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,0,(null as any),(null as any),1,'my-pagination',
      ([] as any[]),(null as any),(null as any),(null as any),View_PaginationComponent_0,
      RenderType_PaginationComponent)),i0.ɵdid(1,49152,(null as any),0,i2.PaginationComponent,
      ([] as any[]),(null as any),(null as any))],(null as any),(null as any));
}
export const PaginationComponentNgFactory:i0.ComponentFactory<i2.PaginationComponent> = i0.ɵccf('my-pagination',
    i2.PaginationComponent,View_PaginationComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvQ2F0YWxpbi9EZXNrdG9wL1Byb2llY3QgbGljZW50YS9hc3NldHMvYXBwL3BhZ2luYXRpb24vcGFnaW5hdGlvbi5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovVXNlcnMvQ2F0YWxpbi9EZXNrdG9wL1Byb2llY3QgbGljZW50YS9hc3NldHMvYXBwL3BhZ2luYXRpb24vcGFnaW5hdGlvbi5jb21wb25lbnQudHMiLCJuZzovLy9DOi9Vc2Vycy9DYXRhbGluL0Rlc2t0b3AvUHJvaWVjdCBsaWNlbnRhL2Fzc2V0cy9hcHAvcGFnaW5hdGlvbi9wYWdpbmF0aW9uLmNvbXBvbmVudC50cy5QYWdpbmF0aW9uQ29tcG9uZW50Lmh0bWwiLCJuZzovLy9DOi9Vc2Vycy9DYXRhbGluL0Rlc2t0b3AvUHJvaWVjdCBsaWNlbnRhL2Fzc2V0cy9hcHAvcGFnaW5hdGlvbi9wYWdpbmF0aW9uLmNvbXBvbmVudC50cy5QYWdpbmF0aW9uQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiXG4gICAgICAgIDxkaXYgY2xhc3M9XCJjb250YWluZXJcIj5cbiAgICAgICAgICAgIDxkaXYgY2xhc3M9XCJyb3cgdGV4dC1jZW50ZXJcIj5cbiAgICAgICAgICAgICAgICA8ZGl2IGNsYXNzPVwicGFnaW5hdGlvblwiPlxuICAgICAgICAgICAgICAgICAgICA8YSBocmVmPVwiI1wiPiZsYXF1bzs8L2E+XG4gICAgICAgICAgICAgICAgICAgIDxhIGhyZWY9XCIjXCIgKm5nRm9yPVwibGV0IHBhZ2Ugb2YgcGFnZXNcIj57e3BhZ2V9fTwvYT5cbiAgICAgICAgICAgICAgICAgICAgPCEtLTxhIGNsYXNzPVwiYWN0aXZlXCIgaHJlZj1cIiNcIj4yPC9hPi0tPlxuICAgICAgICAgICAgICAgICAgICA8YSBocmVmPVwiI1wiPiZyYXF1bzs8L2E+XG4gICAgICAgICAgICAgICAgPC9kaXY+XG4gICAgICAgICAgICA8L2Rpdj5cbiAgICAgICAgPC9kaXY+XG4gICAgIiwiPG15LXBhZ2luYXRpb24+PC9teS1wYWdpbmF0aW9uPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7OztvQkNLb0I7TUFBQTtNQUF1QztJQUFBO0lBQUE7Ozs7b0JBTDNELGtEQUNRO01BQUE7TUFBQSwwREFBdUI7TUFBQSxtQ0FDbkI7TUFBQTtNQUFBLDhCQUE2QjtNQUN6QjtVQUFBO01BQXdCLDhEQUNwQjtVQUFBO1VBQUEsNENBQVk7VUFBQSxRQUFXLDhEQUN2QjtpQkFBQTthQUFBOzRCQUFBLHlDQUFtRDtVQUFBLDJDQUNaO1VBQUEsNkJBQ3ZDO1VBQUE7VUFBQSxnQkFBWSx5Q0FBVztVQUFBLHVDQUNyQjtVQUFBLHFCQUNKLGtEQUNKO2lCQUFBOztJQUxrQjtJQUFaLFlBQVksU0FBWjs7OztvQkNMcEI7TUFBQTtvQ0FBQSxVQUFBO01BQUE7OzsifQ==
