/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '@angular/common';
import * as i2 from './map.component';
import * as i3 from './map.service';
import * as i4 from '../ad/category.service';
import * as i5 from '../ad/ad.service';
import * as i6 from '@angular/router';
const styles_MapComponent:any[] = ['.map[_ngcontent-%COMP%] {\n            width: 100%; \n            height: 400px;\n            box-shadow: 0 0 8px;\n        }'];
export const RenderType_MapComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:0,styles:styles_MapComponent,
    data:{}});
function View_MapComponent_1(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,0,(null as any),(null as any),4,'span',[['class',
      'text-center']],(null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i0.ɵted(-1,(null as any),['\n        '])),(_l()(),i0.ɵeld(2,0,(null as any),
          (null as any),1,'h1',[['class','padding-bottom-md']],(null as any),(null as any),
          (null as any),(null as any),(null as any))),(_l()(),i0.ɵted(-1,(null as any),
          ['Cereri din aproprierea ta:'])),(_l()(),i0.ɵted(-1,(null as any),['\n    ']))],
      (null as any),(null as any));
}
export function View_MapComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,0,(null as any),(null as any),6,'div',[['class',
      'margin-bottom-lg']],(null as any),(null as any),(null as any),(null as any),
      (null as any))),(_l()(),i0.ɵted(-1,(null as any),['\n    '])),(_l()(),i0.ɵand(16777216,
      (null as any),(null as any),1,(null as any),View_MapComponent_1)),i0.ɵdid(3,
      16384,(null as any),0,i1.NgIf,[i0.ViewContainerRef,i0.TemplateRef],{ngIf:[0,
          'ngIf']},(null as any)),(_l()(),i0.ɵted(-1,(null as any),['\n    '])),(_l()(),
      i0.ɵeld(5,0,(null as any),(null as any),0,'div',[['class','map'],['id','map']],
          (null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i0.ɵted(-1,(null as any),['\n']))],(_ck,_v) => {
    var _co:i2.MapComponent = _v.component;
    const currVal_0:boolean = !_co.isUsedForReviews;
    _ck(_v,3,0,currVal_0);
  },(null as any));
}
export function View_MapComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,0,(null as any),(null as any),1,'app-map',([] as any[]),
      (null as any),(null as any),(null as any),View_MapComponent_0,RenderType_MapComponent)),
      i0.ɵdid(1,114688,(null as any),0,i2.MapComponent,[i3.MapService,i4.CategoryService,
          i5.AdService,i6.Router],(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const MapComponentNgFactory:i0.ComponentFactory<i2.MapComponent> = i0.ɵccf('app-map',
    i2.MapComponent,View_MapComponent_Host_0,{lat:'lat',lng:'lng',isUsedForReviews:'isUsedForReviews',
        userRange:'userRange'},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvQ2F0YWxpbi9EZXNrdG9wL1Byb2llY3QgbGljZW50YS9hc3NldHMvYXBwL21hcC9tYXAuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L1VzZXJzL0NhdGFsaW4vRGVza3RvcC9Qcm9pZWN0IGxpY2VudGEvYXNzZXRzL2FwcC9tYXAvbWFwLmNvbXBvbmVudC50cyIsIm5nOi8vL0M6L1VzZXJzL0NhdGFsaW4vRGVza3RvcC9Qcm9pZWN0IGxpY2VudGEvYXNzZXRzL2FwcC9tYXAvbWFwLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovVXNlcnMvQ2F0YWxpbi9EZXNrdG9wL1Byb2llY3QgbGljZW50YS9hc3NldHMvYXBwL21hcC9tYXAuY29tcG9uZW50LnRzLk1hcENvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxkaXYgY2xhc3M9XCJtYXJnaW4tYm90dG9tLWxnXCI+XHJcbiAgICA8c3BhbiBjbGFzcz1cInRleHQtY2VudGVyXCIgKm5nSWY9XCIhaXNVc2VkRm9yUmV2aWV3c1wiPlxyXG4gICAgICAgIDxoMSBjbGFzcz1cInBhZGRpbmctYm90dG9tLW1kXCI+Q2VyZXJpIGRpbiBhcHJvcHJpZXJlYSB0YTo8L2gxPlxyXG4gICAgPC9zcGFuPlxyXG4gICAgPGRpdiBjbGFzcz1cIm1hcFwiIGlkPVwibWFwXCI+PC9kaXY+XHJcbjwvZGl2PiIsIjxhcHAtbWFwPjwvYXBwLW1hcD4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7O29CQ0NJO01BQUE7TUFBb0Qsa0RBQ2hEO1VBQUE7VUFBQSw0Q0FBOEI7VUFBQSxpQ0FBK0I7Ozs7b0JBRnJFO01BQUE7TUFBQSxnQkFBOEIsOENBQzFCO01BQUEseUVBQUE7TUFBQTtVQUFBLHdCQUVPLDhDQUNQO2FBQUE7VUFBQTtNQUFnQzs7SUFITjtJQUExQixXQUEwQixTQUExQjs7OztvQkNESjtNQUFBO2FBQUE7Z0NBQUE7SUFBQTs7Ozs7In0=
