/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './app.module';
import * as i2 from './app.component';
import * as i3 from '../../node_modules/ngx-bootstrap/dropdown/bs-dropdown-container.component.ngfactory';
import * as i4 from './ad/ad-index.component.ngfactory';
import * as i5 from './ad/ad-new.component.ngfactory';
import * as i6 from './ad/ad-list.component.ngfactory';
import * as i7 from './ad/ad-info.component.ngfactory';
import * as i8 from './reviews/review-list.component.ngfactory';
import * as i9 from './offerts/offert-list.component.ngfactory';
import * as i10 from './auth/forgot-password.component.ngfactory';
import * as i11 from './auth/authentication.component.ngfactory';
import * as i12 from './administration/administration.component.ngfactory';
import * as i13 from './app.component.ngfactory';
import * as i14 from '@angular/common';
import * as i15 from '@angular/platform-browser';
import * as i16 from '@angular/forms';
import * as i17 from '@angular/http';
import * as i18 from '@angular/router';
import * as i19 from 'ngx-bootstrap/positioning/positioning.service';
import * as i20 from 'ngx-bootstrap/component-loader/component-loader.factory';
import * as i21 from 'ngx-bootstrap/dropdown/bs-dropdown.state';
import * as i22 from './error/error.service';
import * as i23 from './auth/auth.service';
import * as i24 from './auth/authguard.service';
import * as i25 from './auth/user.service';
import * as i26 from './ad/ad.service';
import * as i27 from './offerts/offert.service';
import * as i28 from './reviews/review.service';
import * as i29 from './map/map.service';
import * as i30 from './search/search.service';
import * as i31 from './ad/category.service';
import * as i32 from './image.service';
import * as i33 from './ad/ad-index.component';
import * as i34 from './ad/ad-new.component';
import * as i35 from './ad/ad-list.component';
import * as i36 from './ad/ad-info.component';
import * as i37 from './reviews/review-list.component';
import * as i38 from './offerts/offert-list.component';
import * as i39 from './auth/forgot-password.component';
import * as i40 from './auth/authentication.component';
import * as i41 from './administration/administration.component';
import * as i42 from 'ngx-bootstrap/dropdown/bs-dropdown.module';
import * as i43 from 'ngx-bootstrap/rating/rating.module';
import * as i44 from 'ngx-bootstrap/dropdown/bs-dropdown.config';
export const AppModuleNgFactory:i0.NgModuleFactory<i1.AppModule> = i0.ɵcmf(i1.AppModule,
    [i2.AppComponent],(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i3.BsDropdownContainerComponentNgFactory,i4.AdIndexComponentNgFactory,
              i5.AdNewComponentNgFactory,i6.AdListComponentNgFactory,i7.AdInfoComponentNgFactory,
              i8.ReviewListComponentNgFactory,i9.OffertListComponentNgFactory,i10.ForgotPasswordComponentNgFactory,
              i11.AuthenticationComponentNgFactory,i12.AdministrationComponentNgFactory,
              i13.AppComponentNgFactory]],[3,i0.ComponentFactoryResolver],i0.NgModuleRef]),
          i0.ɵmpd(5120,i0.LOCALE_ID,i0.ɵm,[[3,i0.LOCALE_ID]]),i0.ɵmpd(4608,i14.NgLocalization,
              i14.NgLocaleLocalization,[i0.LOCALE_ID]),i0.ɵmpd(5120,i0.APP_ID,i0.ɵf,
              ([] as any[])),i0.ɵmpd(5120,i0.IterableDiffers,i0.ɵk,([] as any[])),
          i0.ɵmpd(5120,i0.KeyValueDiffers,i0.ɵl,([] as any[])),i0.ɵmpd(4608,i15.DomSanitizer,
              i15.ɵe,[i14.DOCUMENT]),i0.ɵmpd(6144,i0.Sanitizer,(null as any),[i15.DomSanitizer]),
          i0.ɵmpd(4608,i15.HAMMER_GESTURE_CONFIG,i15.HammerGestureConfig,([] as any[])),
          i0.ɵmpd(5120,i15.EVENT_MANAGER_PLUGINS,(p0_0:any,p1_0:any,p2_0:any,p2_1:any) => {
            return [new i15.ɵDomEventsPlugin(p0_0),new i15.ɵKeyEventsPlugin(p1_0),
                new i15.ɵHammerGesturesPlugin(p2_0,p2_1)];
          },[i14.DOCUMENT,i14.DOCUMENT,i14.DOCUMENT,i15.HAMMER_GESTURE_CONFIG]),i0.ɵmpd(4608,
              i15.EventManager,i15.EventManager,[i15.EVENT_MANAGER_PLUGINS,i0.NgZone]),
          i0.ɵmpd(135680,i15.ɵDomSharedStylesHost,i15.ɵDomSharedStylesHost,[i14.DOCUMENT]),
          i0.ɵmpd(4608,i15.ɵDomRendererFactory2,i15.ɵDomRendererFactory2,[i15.EventManager,
              i15.ɵDomSharedStylesHost]),i0.ɵmpd(6144,i0.RendererFactory2,(null as any),
              [i15.ɵDomRendererFactory2]),i0.ɵmpd(6144,i15.ɵSharedStylesHost,(null as any),
              [i15.ɵDomSharedStylesHost]),i0.ɵmpd(4608,i0.Testability,i0.Testability,
              [i0.NgZone]),i0.ɵmpd(4608,i15.Meta,i15.Meta,[i14.DOCUMENT]),i0.ɵmpd(4608,
              i15.Title,i15.Title,[i14.DOCUMENT]),i0.ɵmpd(4608,i16.ɵi,i16.ɵi,([] as any[])),
          i0.ɵmpd(4608,i16.FormBuilder,i16.FormBuilder,([] as any[])),i0.ɵmpd(4608,
              i17.BrowserXhr,i17.BrowserXhr,([] as any[])),i0.ɵmpd(4608,i17.ResponseOptions,
              i17.BaseResponseOptions,([] as any[])),i0.ɵmpd(5120,i17.XSRFStrategy,
              i17.ɵb,([] as any[])),i0.ɵmpd(4608,i17.XHRBackend,i17.XHRBackend,[i17.BrowserXhr,
              i17.ResponseOptions,i17.XSRFStrategy]),i0.ɵmpd(4608,i17.RequestOptions,
              i17.BaseRequestOptions,([] as any[])),i0.ɵmpd(5120,i17.Http,i17.ɵc,[i17.XHRBackend,
              i17.RequestOptions]),i0.ɵmpd(5120,i18.ActivatedRoute,i18.ɵf,[i18.Router]),
          i0.ɵmpd(4608,i18.NoPreloading,i18.NoPreloading,([] as any[])),i0.ɵmpd(6144,
              i18.PreloadingStrategy,(null as any),[i18.NoPreloading]),i0.ɵmpd(135680,
              i18.RouterPreloader,i18.RouterPreloader,[i18.Router,i0.NgModuleFactoryLoader,
                  i0.Compiler,i0.Injector,i18.PreloadingStrategy]),i0.ɵmpd(4608,i18.PreloadAllModules,
              i18.PreloadAllModules,([] as any[])),i0.ɵmpd(5120,i18.ROUTER_INITIALIZER,
              i18.ɵi,[i18.ɵg]),i0.ɵmpd(5120,i0.APP_BOOTSTRAP_LISTENER,(p0_0:any) => {
            return [p0_0];
          },[i18.ROUTER_INITIALIZER]),i0.ɵmpd(4608,i19.PositioningService,i19.PositioningService,
              ([] as any[])),i0.ɵmpd(4608,i20.ComponentLoaderFactory,i20.ComponentLoaderFactory,
              [i0.ComponentFactoryResolver,i0.NgZone,i0.Injector,i19.PositioningService,
                  i0.ApplicationRef]),i0.ɵmpd(4608,i21.BsDropdownState,i21.BsDropdownState,
              ([] as any[])),i0.ɵmpd(4608,i22.ErrorService,i22.ErrorService,([] as any[])),
          i0.ɵmpd(4608,i23.AuthService,i23.AuthService,[i17.Http,i22.ErrorService]),
          i0.ɵmpd(4608,i24.AuthGuardService,i24.AuthGuardService,[i23.AuthService,
              i18.Router]),i0.ɵmpd(4608,i25.UserService,i25.UserService,[i17.Http,
              i22.ErrorService]),i0.ɵmpd(4608,i26.AdService,i26.AdService,[i17.Http,
              i22.ErrorService]),i0.ɵmpd(4608,i27.OffertService,i27.OffertService,
              [i17.Http]),i0.ɵmpd(4608,i28.ReviewService,i28.ReviewService,[i17.Http]),
          i0.ɵmpd(4608,i29.MapService,i29.MapService,[i17.Http]),i0.ɵmpd(4608,i30.SearchService,
              i30.SearchService,[i17.Http,i29.MapService,i22.ErrorService]),i0.ɵmpd(4608,
              i31.CategoryService,i31.CategoryService,[i17.Http]),i0.ɵmpd(4608,i32.ImageService,
              i32.ImageService,[i17.Http]),i0.ɵmpd(512,i14.CommonModule,i14.CommonModule,
              ([] as any[])),i0.ɵmpd(1024,i0.ErrorHandler,i15.ɵa,([] as any[])),i0.ɵmpd(1024,
              i0.NgProbeToken,() => {
                return [i18.ɵb()];
              },([] as any[])),i0.ɵmpd(512,i18.ɵg,i18.ɵg,[i0.Injector]),i0.ɵmpd(1024,
              i0.APP_INITIALIZER,(p0_0:any,p0_1:any,p1_0:any) => {
                return [i15.ɵc(p0_0,p0_1),i18.ɵh(p1_0)];
              },[[2,i15.NgProbeToken],[2,i0.NgProbeToken],i18.ɵg]),i0.ɵmpd(512,i0.ApplicationInitStatus,
              i0.ApplicationInitStatus,[[2,i0.APP_INITIALIZER]]),i0.ɵmpd(131584,i0.ɵe,
              i0.ɵe,[i0.NgZone,i0.ɵConsole,i0.Injector,i0.ErrorHandler,i0.ComponentFactoryResolver,
                  i0.ApplicationInitStatus]),i0.ɵmpd(2048,i0.ApplicationRef,(null as any),
              [i0.ɵe]),i0.ɵmpd(512,i0.ApplicationModule,i0.ApplicationModule,[i0.ApplicationRef]),
          i0.ɵmpd(512,i15.BrowserModule,i15.BrowserModule,[[3,i15.BrowserModule]]),
          i0.ɵmpd(512,i16.ɵba,i16.ɵba,([] as any[])),i0.ɵmpd(512,i16.FormsModule,i16.FormsModule,
              ([] as any[])),i0.ɵmpd(1024,i18.ɵa,i18.ɵd,[[3,i18.Router]]),i0.ɵmpd(512,
              i18.UrlSerializer,i18.DefaultUrlSerializer,([] as any[])),i0.ɵmpd(512,
              i18.ChildrenOutletContexts,i18.ChildrenOutletContexts,([] as any[])),
          i0.ɵmpd(256,i18.ROUTER_CONFIGURATION,{},([] as any[])),i0.ɵmpd(1024,i14.LocationStrategy,
              i18.ɵc,[i14.PlatformLocation,[2,i14.APP_BASE_HREF],i18.ROUTER_CONFIGURATION]),
          i0.ɵmpd(512,i14.Location,i14.Location,[i14.LocationStrategy]),i0.ɵmpd(512,
              i0.Compiler,i0.Compiler,([] as any[])),i0.ɵmpd(512,i0.NgModuleFactoryLoader,
              i0.SystemJsNgModuleLoader,[i0.Compiler,[2,i0.SystemJsNgModuleLoaderConfig]]),
          i0.ɵmpd(1024,i18.ROUTES,() => {
            return [[{path:'',redirectTo:'/index',pathMatch:'full'},{path:'index',
                component:i33.AdIndexComponent},{path:'anunturi/anunt-nou/:id',component:i34.AdNewComponent,
                canActivate:[i24.AuthGuardService]},{path:'anunturi/anunt-nou',component:i34.AdNewComponent,
                canActivate:[i24.AuthGuardService]},{path:'anunturi/:categorie',component:i35.AdListComponent},
                {path:'anunturi/:categorie/:id',component:i36.AdInfoComponent,canActivate:[i24.AuthGuardService]},
                {path:'anunturi',component:i35.AdListComponent},{path:'review/:id',
                    component:i37.ReviewListComponent,canActivate:[i24.AuthGuardService]},
                {path:'oferte',component:i38.OffertListComponent,canActivate:[i24.AuthGuardService]},
                {path:'auth/new-password',component:i39.ForgotPasswordComponent},{path:'auth',
                    component:i40.AuthenticationComponent},{path:'my-account',component:i41.AdministrationComponent,
                    canActivate:[i24.AuthGuardService]},{path:'*',redirectTo:'/anunturi'}]];
          },([] as any[])),i0.ɵmpd(1024,i18.Router,i18.ɵe,[i0.ApplicationRef,i18.UrlSerializer,
              i18.ChildrenOutletContexts,i14.Location,i0.Injector,i0.NgModuleFactoryLoader,
              i0.Compiler,i18.ROUTES,i18.ROUTER_CONFIGURATION,[2,i18.UrlHandlingStrategy],
              [2,i18.RouteReuseStrategy]]),i0.ɵmpd(512,i18.RouterModule,i18.RouterModule,
              [[2,i18.ɵa],[2,i18.Router]]),i0.ɵmpd(512,i16.ReactiveFormsModule,i16.ReactiveFormsModule,
              ([] as any[])),i0.ɵmpd(512,i17.HttpModule,i17.HttpModule,([] as any[])),
          i0.ɵmpd(512,i42.BsDropdownModule,i42.BsDropdownModule,([] as any[])),i0.ɵmpd(512,
              i43.RatingModule,i43.RatingModule,([] as any[])),i0.ɵmpd(512,i1.AppModule,
              i1.AppModule,([] as any[])),i0.ɵmpd(256,i44.BsDropdownConfig,{autoClose:true},
              ([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvQ2F0YWxpbi9EZXNrdG9wL1Byb2llY3QgbGljZW50YS9hc3NldHMvYXBwL2FwcC5tb2R1bGUubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovVXNlcnMvQ2F0YWxpbi9EZXNrdG9wL1Byb2llY3QgbGljZW50YS9hc3NldHMvYXBwL2FwcC5tb2R1bGUudHMiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
