/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './search/search.component.ngfactory';
import * as i2 from './search/search.component';
import * as i3 from './search/search.service';
import * as i4 from './ad/category.service';
import * as i5 from '@angular/router';
import * as i6 from './header.component.ngfactory';
import * as i7 from './header.component';
import * as i8 from './auth/auth.service';
import * as i9 from './offerts/offert.service';
import * as i10 from '@angular/common';
import * as i11 from './footer.component.ngfactory';
import * as i12 from './footer.component';
import * as i13 from './error/error.component.ngfactory';
import * as i14 from './error/error.component';
import * as i15 from './error/error.service';
import * as i16 from './app.component';
import * as i17 from './messages/message.service';
import * as i18 from '@angular/http';
const styles_AppComponent:any[] = ([] as any[]);
export const RenderType_AppComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,styles:styles_AppComponent,
    data:{}});
function View_AppComponent_1(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,0,(null as any),(null as any),1,'my-search',
      ([] as any[]),(null as any),(null as any),(null as any),i1.View_SearchComponent_0,
      i1.RenderType_SearchComponent)),i0.ɵdid(1,114688,(null as any),0,i2.SearchComponent,
      [i3.SearchService,i4.CategoryService,i5.Router],(null as any),(null as any))],
      (_ck,_v) => {
        _ck(_v,1,0);
      },(null as any));
}
export function View_AppComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,0,(null as any),(null as any),1,'app-header',
      ([] as any[]),(null as any),(null as any),(null as any),i6.View_HeaderComponent_0,
      i6.RenderType_HeaderComponent)),i0.ɵdid(1,114688,(null as any),0,i7.HeaderComponent,
      [i8.AuthService,i9.OffertService],(null as any),(null as any)),(_l()(),i0.ɵted(-1,
      (null as any),['\n'])),(_l()(),i0.ɵand(16777216,(null as any),(null as any),
      1,(null as any),View_AppComponent_1)),i0.ɵdid(4,16384,(null as any),0,i10.NgIf,
      [i0.ViewContainerRef,i0.TemplateRef],{ngIf:[0,'ngIf']},(null as any)),(_l()(),
      i0.ɵted(-1,(null as any),['\n'])),(_l()(),i0.ɵeld(6,16777216,(null as any),(null as any),
      1,'router-outlet',([] as any[]),(null as any),(null as any),(null as any),(null as any),
      (null as any))),i0.ɵdid(7,212992,(null as any),0,i5.RouterOutlet,[i5.ChildrenOutletContexts,
      i0.ViewContainerRef,i0.ComponentFactoryResolver,[8,(null as any)],i0.ChangeDetectorRef],
      (null as any),(null as any)),(_l()(),i0.ɵted(-1,(null as any),['\n'])),(_l()(),
      i0.ɵeld(9,0,(null as any),(null as any),1,'app-footer',([] as any[]),(null as any),
          (null as any),(null as any),i11.View_FooterComponent_0,i11.RenderType_FooterComponent)),
      i0.ɵdid(10,49152,(null as any),0,i12.FooterComponent,([] as any[]),(null as any),
          (null as any)),(_l()(),i0.ɵted(-1,(null as any),['\n'])),(_l()(),i0.ɵeld(12,
          0,(null as any),(null as any),1,'app-error',([] as any[]),(null as any),
          (null as any),(null as any),i13.View_ErrorComponent_0,i13.RenderType_ErrorComponent)),
      i0.ɵdid(13,114688,(null as any),0,i14.ErrorComponent,[i15.ErrorService],(null as any),
          (null as any))],(_ck,_v) => {
    var _co:i16.AppComponent = _v.component;
    _ck(_v,1,0);
    const currVal_0:any = ((_co.router.url.toString() == '/index') || (_co.router.url.toString() == '/anunturi'));
    _ck(_v,4,0,currVal_0);
    _ck(_v,7,0);
    _ck(_v,13,0);
  },(null as any));
}
export function View_AppComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,0,(null as any),(null as any),2,'my-app',([] as any[]),
      (null as any),(null as any),(null as any),View_AppComponent_0,RenderType_AppComponent)),
      i0.ɵprd(4608,(null as any),i17.MessageService,i17.MessageService,[i18.Http,i15.ErrorService]),
      i0.ɵdid(2,49152,(null as any),0,i16.AppComponent,[i5.Router],(null as any),(null as any))],
      (null as any),(null as any));
}
export const AppComponentNgFactory:i0.ComponentFactory<i16.AppComponent> = i0.ɵccf('my-app',
    i16.AppComponent,View_AppComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvQ2F0YWxpbi9EZXNrdG9wL1Byb2llY3QgbGljZW50YS9hc3NldHMvYXBwL2FwcC5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vQzovVXNlcnMvQ2F0YWxpbi9EZXNrdG9wL1Byb2llY3QgbGljZW50YS9hc3NldHMvYXBwL2FwcC5jb21wb25lbnQudHMiLCJuZzovLy9DOi9Vc2Vycy9DYXRhbGluL0Rlc2t0b3AvUHJvaWVjdCBsaWNlbnRhL2Fzc2V0cy9hcHAvYXBwLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovVXNlcnMvQ2F0YWxpbi9EZXNrdG9wL1Byb2llY3QgbGljZW50YS9hc3NldHMvYXBwL2FwcC5jb21wb25lbnQudHMuQXBwQ29tcG9uZW50X0hvc3QuaHRtbCJdLCJzb3VyY2VzQ29udGVudCI6WyIgIiwiPGFwcC1oZWFkZXI+PC9hcHAtaGVhZGVyPlxyXG48bXktc2VhcmNoICpuZ0lmPVwicm91dGVyLnVybC50b1N0cmluZygpID09ICcvaW5kZXgnIHx8IHJvdXRlci51cmwudG9TdHJpbmcoKSA9PSAnL2FudW50dXJpJ1wiPjwvbXktc2VhcmNoPlxyXG48cm91dGVyLW91dGxldD48L3JvdXRlci1vdXRsZXQ+XHJcbjxhcHAtZm9vdGVyPjwvYXBwLWZvb3Rlcj5cclxuPGFwcC1lcnJvcj48L2FwcC1lcnJvcj4iLCI8bXktYXBwPjwvbXktYXBwPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7b0JDQ0E7TUFBQTttQ0FBQSxVQUFBO01BQUE7O1FBQUE7Ozs7b0JBREE7TUFBQTttQ0FBQSxVQUFBO01BQUEsK0RBQXlCO01BQUEsdUJBQ3pCO01BQUEsNkNBQUE7TUFBQSxzRUFBeUc7YUFBQSwyQkFDekc7TUFBQTtNQUFBLHVCQUFBO3NEQUFBO01BQUEsNkJBQStCLDBDQUMvQjthQUFBO1VBQUE7YUFBQTtVQUFBLGVBQXlCLDBDQUN6QjtVQUFBO1VBQUE7YUFBQTtVQUFBOztJQUpBO0lBQ1c7SUFBWCxXQUFXLFNBQVg7SUFDQTtJQUVBOzs7O29CQ0pBO01BQUE7YUFBQTthQUFBOzs7OyJ9
