/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './ad-admin.component.ngfactory';
import * as i2 from './ad-admin.component';
import * as i3 from '../../ad/ad.service';
import * as i4 from '../../image.service';
import * as i5 from '@angular/common';
import * as i6 from './ad-list-admin.component';
const styles_AdListAdminComponent:any[] = [''];
export const RenderType_AdListAdminComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:0,
    styles:styles_AdListAdminComponent,data:{}});
function View_AdListAdminComponent_2(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,0,(null as any),(null as any),4,'div',[['class',
      'row']],(null as any),(null as any),(null as any),(null as any),(null as any))),
      (_l()(),i0.ɵted(-1,(null as any),['\n        '])),(_l()(),i0.ɵeld(2,0,(null as any),
          (null as any),1,'my-ad-admin',([] as any[]),(null as any),[[(null as any),
              'removeEvent']],(_v,en,$event) => {
            var ad:boolean = true;
            var _co:any = _v.component;
            if (('removeEvent' === en)) {
              const pd_0:any = ((<any>_co.onDeleteAd($event)) !== false);
              ad = (pd_0 && ad);
            }
            return ad;
          },i1.View_AdAdminComponent_0,i1.RenderType_AdAdminComponent)),i0.ɵdid(3,
          114688,(null as any),0,i2.AdAdminComponent,[i3.AdService,i4.ImageService],
          {ad:[0,'ad']},{removeEvent:'removeEvent'}),(_l()(),i0.ɵted(-1,(null as any),
          ['\n    ']))],(_ck,_v) => {
    const currVal_0:any = _v.context.$implicit;
    _ck(_v,3,0,currVal_0);
  },(null as any));
}
function View_AdListAdminComponent_1(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,0,(null as any),(null as any),4,'div',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i0.ɵted(-1,(null as any),['\n    '])),(_l()(),i0.ɵand(16777216,(null as any),
      (null as any),1,(null as any),View_AdListAdminComponent_2)),i0.ɵdid(3,802816,
      (null as any),0,i5.NgForOf,[i0.ViewContainerRef,i0.TemplateRef,i0.IterableDiffers],
      {ngForOf:[0,'ngForOf']},(null as any)),(_l()(),i0.ɵted(-1,(null as any),['\n']))],
      (_ck,_v) => {
        var _co:any = _v.component;
        const currVal_0:any = _co.userAds;
        _ck(_v,3,0,currVal_0);
      },(null as any));
}
function View_AdListAdminComponent_3(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵted(-1,(null as any),['\n    '])),(_l()(),i0.ɵeld(1,
      0,(null as any),(null as any),1,'div',[['class','alert alert-warning text-center']],
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i0.ɵted(-1,(null as any),['Momentan nu aveti niciun anunt activ.'])),(_l()(),
      i0.ɵted(-1,(null as any),['\n']))],(null as any),(null as any));
}
export function View_AdListAdminComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵand(16777216,(null as any),(null as any),1,(null as any),
      View_AdListAdminComponent_1)),i0.ɵdid(1,16384,(null as any),0,i5.NgIf,[i0.ViewContainerRef,
      i0.TemplateRef],{ngIf:[0,'ngIf'],ngIfElse:[1,'ngIfElse']},(null as any)),(_l()(),
      i0.ɵted(-1,(null as any),['\n'])),(_l()(),i0.ɵand(0,[['showAds',2]],(null as any),
      0,(null as any),View_AdListAdminComponent_3))],(_ck,_v) => {
    var _co:i6.AdListAdminComponent = _v.component;
    const currVal_0:any = ((_co.userAds !== (undefined as any)) && (_co.userAds.length > 0));
    const currVal_1:any = i0.ɵnov(_v,3);
    _ck(_v,1,0,currVal_0,currVal_1);
  },(null as any));
}
export function View_AdListAdminComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,0,(null as any),(null as any),1,'my-ad-list-admin',
      ([] as any[]),(null as any),(null as any),(null as any),View_AdListAdminComponent_0,
      RenderType_AdListAdminComponent)),i0.ɵdid(1,114688,(null as any),0,i6.AdListAdminComponent,
      [i3.AdService],(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const AdListAdminComponentNgFactory:i0.ComponentFactory<i6.AdListAdminComponent> = i0.ɵccf('my-ad-list-admin',
    i6.AdListAdminComponent,View_AdListAdminComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovVXNlcnMvQ2F0YWxpbi9EZXNrdG9wL1Byb2llY3QgbGljZW50YS9hc3NldHMvYXBwL2FkbWluaXN0cmF0aW9uL215LWFkcy9hZC1saXN0LWFkbWluLmNvbXBvbmVudC5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9Vc2Vycy9DYXRhbGluL0Rlc2t0b3AvUHJvaWVjdCBsaWNlbnRhL2Fzc2V0cy9hcHAvYWRtaW5pc3RyYXRpb24vbXktYWRzL2FkLWxpc3QtYWRtaW4uY29tcG9uZW50LnRzIiwibmc6Ly8vQzovVXNlcnMvQ2F0YWxpbi9EZXNrdG9wL1Byb2llY3QgbGljZW50YS9hc3NldHMvYXBwL2FkbWluaXN0cmF0aW9uL215LWFkcy9hZC1saXN0LWFkbWluLmNvbXBvbmVudC5odG1sIiwibmc6Ly8vQzovVXNlcnMvQ2F0YWxpbi9EZXNrdG9wL1Byb2llY3QgbGljZW50YS9hc3NldHMvYXBwL2FkbWluaXN0cmF0aW9uL215LWFkcy9hZC1saXN0LWFkbWluLmNvbXBvbmVudC50cy5BZExpc3RBZG1pbkNvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxkaXYgKm5nSWY9XCJ1c2VyQWRzICE9PSB1bmRlZmluZWQgJiYgdXNlckFkcy5sZW5ndGg+MDsgZWxzZSBzaG93QWRzXCI+XHJcbiAgICA8ZGl2IGNsYXNzPVwicm93XCIgKm5nRm9yPVwibGV0IGFkIG9mIHVzZXJBZHNcIj5cclxuICAgICAgICA8bXktYWQtYWRtaW4gW2FkXT1cImFkXCIgKHJlbW92ZUV2ZW50KT1cIm9uRGVsZXRlQWQoJGV2ZW50KVwiPjwvbXktYWQtYWRtaW4+XHJcbiAgICA8L2Rpdj5cclxuPC9kaXY+XHJcbjxuZy10ZW1wbGF0ZSAjc2hvd0Fkcz5cclxuICAgIDxkaXYgY2xhc3M9XCJhbGVydCBhbGVydC13YXJuaW5nIHRleHQtY2VudGVyXCI+TW9tZW50YW4gbnUgYXZldGkgbmljaXVuIGFudW50IGFjdGl2LjwvZGl2PlxyXG48L25nLXRlbXBsYXRlPiIsIjxteS1hZC1saXN0LWFkbWluPjwvbXktYWQtbGlzdC1hZG1pbj4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7O29CQ0NJO01BQUE7TUFBNEMsa0RBQ3hDO1VBQUE7Y0FBQTtZQUFBO1lBQUE7WUFBdUI7Y0FBQTtjQUFBO1lBQUE7WUFBdkI7VUFBQSxxRUFBQTtVQUFBO1VBQUEsMkNBQXdFO1VBQUE7SUFBM0Q7SUFBYixXQUFhLFNBQWI7Ozs7b0JBRlI7TUFBQSx3RUFBcUU7YUFBQSwrQkFDakU7TUFBQSxtRUFBQTtNQUFBO01BQUEsdUNBRU07OztRQUZXO1FBQWpCLFdBQWlCLFNBQWpCOzs7O29CQUlrQiw4Q0FDbEI7TUFBQTtNQUFBLHdFQUE2QzthQUFBLDhEQUEyQzthQUFBOzs7b0JBTjVGO01BQUEscUNBQUE7b0JBQUEsMkRBSU07YUFBQSwyQkFDTjtNQUFBOztJQUxLO0lBQUE7SUFBTCxXQUFLLG1CQUFMOzs7O29CQ0FBO01BQUE7cUNBQUEsVUFBQTtNQUFBO0lBQUE7Ozs7In0=
